### ISSUE TITLE
Delete thumbnails on media library delete?

### ISSUE THREAD

**Issue by daltonrooney** [MatthewRuddy/Wordpress-Timthumb-alternative#1]
Hey, this looks like a promising script. Just wondering what happens when the main image is deleted from the media library - are the thumbnails removed as well? I've found with VTResize that old thumbnails stick around and sometimes become associated with new images with the same filename.

**Comment by MatthewRuddy** [comment]
Definitely a thought that has gone through my head as well, but probably quite difficult to achieve. Actually generating the resized image isn't the fastest process around, so once it has been done once it is a good idea to try and not have to do it again.

A script could be created to wipe the thumbnails from the uploads folder every day/month/year, but having to regenerate the resized images all over again would take a long time. Might only result in one user having to wait a few extra seconds upon page load, but still not ideal.

I may give it a try in the future, would really be up to how users would like the script to deal with this. If everyone is fine with the possibility of one additional slower page load per regeneration cycle, then I'm sure I can come up with something extra.

**Comment by daltonrooney** [comment]
Rather than some kind of scheduled cleanup, I was thinking only of removing the thumbnails on an actual user media delete. It's possible to hook into wp_delete_attachment(), I guess it's just a matter of finding the filename from the attachment ID and then deleting all of the generated thumbnails. I think a regex would be necessary so that other similar filenames weren't deleted.

http://codex.wordpress.org/Function_Reference/wp_delete_attachment

**Comment by MatthewRuddy** [comment]
Great idea there, much better than my own suggestion! Hadn't thought of it. Can't imagine it would be too difficult to achieve, I'll have a look at it as soon as I can!

**Comment by daltonrooney** [comment]
Cool, I might also give it a try (it should work the same for VT_Resize) so if I am able to get it working I'll share the code.

**Comment by MatthewRuddy** [comment]
Please do, looking forward to it!

-- Just been having a look into it. Not sure how to handle images that aren't in the Media Library? Shouldn't be a problem with image attachments, because they have post IDs. Any ideas?

**Comment by MatthewRuddy** [comment]
I've added functionality for this now. Function will successfully delete resized images from uploads folder when the original Media Library image is deleted. Seems to be working well. However, this does restrict the function to only working with Media Library images. Probably a good thing anyway.
