### ISSUE TITLE
Width/Height being overridden

### ISSUE THREAD

**Issue by nickbuddendotcom** [MatthewRuddy/Wordpress-Timthumb-alternative#13]
Hi, thanks for the great script. 

Maybe I'm wrong but near the top of matthewruddy_image_resize() for WP 3.5+ you've got:

$width  = ( $width )  ? get_option( 'thumbnail_size_w' ) : $width;
$height = ( $height ) ? get_option( 'thumbnail_size_h' ) : $height;

Isn't this backwards? Shouldn't it use get_option when $width/$height are NOT set? Something like:

$width  = ( !isset($width) )  ? get_option( 'thumbnail_size_w' ) : $width;
$height = ( !isset($height) ) ? get_option( 'thumbnail_size_h' ) : $height;

Also I've got to declare global $wp_version; to get into this function.

**Comment by matt2314** [comment]
Agree, switched it around to make it work for me, otherwise everything will be resized to default values:

$width = ( $width )  ? $width : get_option( 'thumbnail_size_w' );
$height = ( $height ) ? $height : get_option( 'thumbnail_size_h' );

Same in the fallback function.

**Comment by MatthewRuddy** [comment]
Bug from a recent pull request - my sincere apologies! Fixed now.
