### ISSUE TITLE
Line 45/46 & 178/179 causing fatal error

### ISSUE THREAD

**Issue by proframework** [MatthewRuddy/Wordpress-Timthumb-alternative#7]
Love the script - was working perfect on my localhost, then I uploaded to my server and was given a fatal error because of these four lines. 

$width = $width ?: get_option( 'thumbnail_size_w' );
$height = $height ?: get_option( 'thumbnail_size_h' );

Seems the server didn't like the ?: syntax.

I commented these lines out for now and the script still works.

Any idea why this would happen?

Thanks!

**Comment by aristath** [comment]
Just wanted to let you know that I too encountered this issue and commenting these lines solves the problem.
After all, they're just there to load the defaults.

**Comment by proframework** [comment]
Cool - just wanted to make sure they weren't doing anything important.

Thanks!

**Comment by MatthewRuddy** [comment]
Problem with older versions of PHP. Those lines were modified by a previous pull request: bit of code shortcutting trickery. Going to fix it now :)
